### create heatmap from 2 document edits

POST localhost/difference-calc/heatmap
Content-Type: application/json

< ./inputs/same-document-twice.json


### different mentions should result in higher/lower score for the token

POST localhost/difference-calc/heatmap
Content-Type: application/json

< ./inputs/one-sentence-different-mentions.json


### different token list should result in error

POST localhost/difference-calc/heatmap
Content-Type: application/json

< ./inputs/different-tokens.json