### create jaccard similarity from 2 same document edits should result in scores of 1

POST localhost/difference-calc/jaccard-index
Content-Type: application/json

< ./inputs/list/same-document-twice.json


### different mentions should have a result < 1

POST localhost/difference-calc/jaccard-index
Content-Type: application/json

< ./inputs/list/one-sentence-different-mentions.json


### different token list should result in error

POST localhost/difference-calc/jaccard-index
Content-Type: application/json

< ./inputs/list/different-tokens.json

### list with only one element should result in error

POST localhost/difference-calc/jaccard-index
Content-Type: application/json

< ./inputs/list/list-with-only-one-element.json